[build]
  base = "."
  publish = "frontend/dist"
  command = "npm install --prefix backend && npm install --prefix frontend && npm run build --prefix frontend"

[functions]
  directory = "backend/api"
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/index"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
